### ISSUE TITLE
NDITH keyword in OPE file template for N-dither imaging mode

### ISSUE THREAD

**Issue by monodera** [naojsoft/qplan#1]
When `Dither=N` is set in the instrument configuration, the corresponding OPE file generated by `qplan` is the following.

```
SetupField $DEF_IMAGEN $T1 INSROT_PA=0.0 OFFSET_RA=0 OFFSET_DEC=0 Filter="HSC-r2"  NDITH=NDITH=5 RDITH=720.0 TDITH=27.0 SKIP=0 STOP=5
```

However, `NDITH=NDITH=5` should be `NDITH=5`.  This appear to happen only in `SetupField` and `Dither=N` in the Phase 2 sheet.

**Comment by ejeschke** [comment]
@monodera, I have fixed this in the latest commit.  I'll update the summit version, you may want to do a pull and reinstall to fix your copy.
