### ISSUE TITLE
Problem with Python > 3.5

### ISSUE THREAD

**Issue by ejeschke** [naojsoft/qplan#17]
There is an issue with scheduling when using Python > 3.5.  The suggestion has been made that it has something to do with the [`datetime` change in Python 3.6](https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep495)

We need a workaround or fix for this to be able to use up to date versions of Python.

**Comment by ejeschke** [comment]
@monodera, I found and fixed the issue where we cannot use python > 3.5.  Fix is in master.

**Comment by monodera** [comment]
Thanks! I've updated my local version.
